import {
  getVariations as getVariationsCore,
  getVariationItems as getVariationItemsCore,
  getItemVariation as getItemVariationCore,
} from '@standardsets/core'

export enum VariationKey {
  NAME = 'name',
  CODE = 'code',
  NUMBER = 'number',
  SYMBOL = 'symbol',
}

export const dataset = {
  name: 'Currencies',
  description: '',
  variations: [
    {
      name: 'Name',
      nameShort: 'Name',
      description: '',
      key: VariationKey.NAME,
      locale: 'en-US',
      index: 0,
    },
    {
      name: 'Code',
      nameShort: 'Code',
      description: '',
      key: VariationKey.CODE,
      locale: 'en-US',
      index: 1,
    },
    {
      name: 'Number',
      nameShort: 'Number',
      description: '',
      key: VariationKey.NUMBER,
      locale: 'en-US',
      index: 3,
    },
    {
      name: 'Symbol',
      nameShort: 'Symbol',
      description: '',
      key: VariationKey.SYMBOL,
      locale: 'en-US',
      index: 4,
    },
  ],
  data: [
    ['United Arab Emirates dirham', 'AED', '784', 'د.إ'],
    ['Afghan afghani', 'AFN', '971', '؋'],
    ['Albanian lek', 'ALL', '008', 'L'],
    ['Armenian dram', 'AMD', '051', 'դր.'],
    ['Netherlands Antillean guilder', 'ANG', '532', 'ƒ'],
    ['Angolan kwanza', 'AOA', '973', 'Kz'],
    ['Argentine peso', 'ARS', '032', '$'],
    ['Australian dollar', 'AUD', '036', '$'],
    ['Aruban florin', 'AWG', '533', 'ƒ'],
    ['Azerbaijani manat', 'AZN', '944', '₼'],
    ['Bosnia and Herzegovina convertible mark', 'BAM', '977', 'KM'],
    ['Barbados dollar', 'BBD', '052', '$'],
    ['Bangladeshi taka', 'BDT', '050', '৳'],
    ['Bulgarian lev', 'BGN', '975', 'лв.'],
    ['Bahraini dinar', 'BHD', '048', '.د.ب'],
    ['Burundian franc', 'BIF', '108', 'Fr'],
    ['Bermudian dollar', 'BMD', '060', '$'],
    ['Brunei dollar', 'BND', '096', '$'],
    ['Boliviano', 'BOB', '068', 'Bs.'],
    ['Brazilian real', 'BRL', '986', 'R$'],
    ['Bahamian dollar', 'BSD', '044', '$'],
    ['Bhutanese ngultrum', 'BTN', '064', 'Nu.'],
    ['Botswana pula', 'BWP', '072', 'P'],
    ['Belarusian ruble', 'BYN', '933', 'Br'],
    ['Belize dollar', 'BZD', '084', '$'],
    ['Canadian dollar', 'CAD', '124', '$'],
    ['Congolese franc', 'CDF', '976', 'Fr'],
    ['Swiss franc', 'CHF', '756', 'Fr'],
    ['Chilean peso', 'CLP', '152', '$'],
    ['Chinese yuan', 'CNY', '156', '¥'],
    ['Colombian peso', 'COP', '170', '$'],
    ['Costa Rican colon', 'CRC', '188', '₡'],
    ['Cuban convertible peso', 'CUC', '931', '$'],
    ['Cuban peso', 'CUP', '192', '$'],
    ['Cape Verde escudo', 'CVE', '132', '$'],
    ['Czech koruna', 'CZK', '203', 'Kč'],
    ['Djiboutian franc', 'DJF', '262', 'Fr'],
    ['Danish krone', 'DKK', '208', 'kr'],
    ['Dominican peso', 'DOP', '214', '$'],
    ['Algerian dinar', 'DZD', '012', 'د.ج'],
    ['Egyptian pound', 'EGP', '818', '£'],
    ['Eritrean nakfa', 'ERN', '232', 'Nfk'],
    ['Ethiopian birr', 'ETB', '230', 'Br'],
    ['Euro', 'EUR', '978', '€'],
    ['Fiji dollar', 'FJD', '242', '$'],
    ['Falkland Islands pound', 'FKP', '238', '£'],
    ['Pound sterling', 'GBP', '826', '£'],
    ['Georgian lari', 'GEL', '981', '₾'],
    ['Ghanaian cedi', 'GHS', '936', '₵'],
    ['Gibraltar pound', 'GIP', '292', '£'],
    ['Gambian dalasi', 'GMD', '270', 'D'],
    ['Guinean franc', 'GNF', '324', 'Fr'],
    ['Guatemalan quetzal', 'GTQ', '320', 'Q'],
    ['Guyanese dollar', 'GYD', '328', '$'],
    ['Hong Kong dollar', 'HKD', '344', '$'],
    ['Honduran lempira', 'HNL', '340', 'L'],
    ['Croatian kuna', 'HRK', '191', 'kn'],
    ['Haitian gourde', 'HTG', '332', 'G'],
    ['Hungarian forint', 'HUF', '348', 'Ft'],
    ['Indonesian rupiah', 'IDR', '360', 'Rp'],
    ['Israeli new shekel', 'ILS', '376', '₪'],
    ['Indian rupee', 'INR', '356', '₹'],
    ['Iraqi dinar', 'IQD', '368', 'ع.د'],
    ['Iranian rial', 'IRR', '364', '﷼'],
    ['Icelandic króna', 'ISK', '352', 'kr'],
    ['Jamaican dollar', 'JMD', '388', '$'],
    ['Jordanian dinar', 'JOD', '400', 'د.ا'],
    ['Japanese yen', 'JPY', '392', '¥'],
    ['Kenyan shilling', 'KES', '404', 'Sh'],
    ['Kyrgyzstani som', 'KGS', '417', 'с'],
    ['Cambodian riel', 'KHR', '116', '៛'],
    ['Comoro franc', 'KMF', '174', 'Fr'],
    ['North Korean won', 'KPW', '408', '₩'],
    ['South Korean won', 'KRW', '410', '₩'],
    ['Kuwaiti dinar', 'KWD', '414', 'د.ك'],
    ['Cayman Islands dollar', 'KYD', '136', '$'],
    ['Kazakhstani tenge', 'KZT', '398', '₸'],
    ['Lao kip', 'LAK', '418', '₭'],
    ['Lebanese pound', 'LBP', '422', 'ل.ل'],
    ['Sri Lankan rupee', 'LKR', '144', 'Rs'],
    ['Liberian dollar', 'LRD', '430', '$'],
    ['Lesotho loti', 'LSL', '426', 'L'],
    ['Libyan dinar', 'LYD', '434', 'ل.د'],
    ['Moroccan dirham', 'MAD', '504', 'د.م.'],
    ['Moldovan leu', 'MDL', '498', 'L'],
    ['Malagasy ariary', 'MGA', '969', 'Ar'],
    ['Macedonian denar', 'MKD', '807', 'ден'],
    ['Myanmar kyat', 'MMK', '104', 'Ks'],
    ['Mongolian tögrög', 'MNT', '496', '₮'],
    ['Macanese pataca', 'MOP', '446', 'P'],
    ['Mauritanian ouguiya', 'MRU', '929', 'UM'],
    ['Mauritian rupee', 'MUR', '480', '₨'],
    ['Maldivian rufiyaa', 'MVR', '462', 'ރ.'],
    ['Malawian kwacha', 'MWK', '454', 'MK'],
    ['Mexican peso', 'MXN', '484', '$'],
    ['Malaysian ringgit', 'MYR', '458', 'RM'],
    ['Mozambican metical', 'MZN', '943', 'MT'],
    ['Namibian dollar', 'NAD', '516', '$'],
    ['Nigerian naira', 'NGN', '566', '₦'],
    ['Nicaraguan córdoba', 'NIO', '558', 'C$'],
    ['Norwegian krone', 'NOK', '578', 'kr'],
    ['Nepalese rupee', 'NPR', '524', '₨'],
    ['New Zealand dollar', 'NZD', '554', '$'],
    ['Omani rial', 'OMR', '512', 'ر.ع.'],
    ['Panamanian balboa', 'PAB', '590', 'B/.'],
    ['Peruvian sol', 'PEN', '604', 'S/.'],
    ['Papua New Guinean kina', 'PGK', '598', 'K'],
    ['Philippine peso', 'PHP', '608', '₱'],
    ['Pakistani rupee', 'PKR', '586', '₨'],
    ['Polish złoty', 'PLN', '985', 'zł'],
    ['Paraguayan guaraní', 'PYG', '600', '₲'],
    ['Qatari riyal', 'QAR', '634', 'ر.ق'],
    ['Romanian leu', 'RON', '946', 'lei'],
    ['Serbian dinar', 'RSD', '941', 'дин.'],
    ['Russian ruble', 'RUB', '643', '₽'],
    ['Rwandan franc', 'RWF', '646', 'Fr'],
    ['Saudi riyal', 'SAR', '682', 'ر.س'],
    ['Solomon Islands dollar', 'SBD', '090', '$'],
    ['Seychelles rupee', 'SCR', '690', '₨'],
    ['Sudanese pound', 'SDG', '938', 'ج.س.'],
    ['Swedish krona', 'SEK', '752', 'kr'],
    ['Singapore dollar', 'SGD', '702', '$'],
    ['Saint Helena pound', 'SHP', '654', '£'],
    ['Sierra Leonean leone', 'SLL', '694', 'Le'],
    ['Somali shilling', 'SOS', '706', 'Sh'],
    ['Surinamese dollar', 'SRD', '968', '$'],
    ['South Sudanese pound', 'SSP', '728', '£'],
    ['São Tomé and Príncipe dobra', 'STN', '930', 'Db'],
    ['Syrian pound', 'SYP', '760', '£'],
    ['Swazi lilangeni', 'SZL', '748', 'L'],
    ['Thai baht', 'THB', '764', '฿'],
    ['Tajikistani somoni', 'TJS', '972', 'ЅМ'],
    ['Turkmenistan manat', 'TMT', '934', 'm'],
    ['Tunisian dinar', 'TND', '788', 'د.ت'],
    ['Tongan paʻanga', 'TOP', '776', 'T$'],
    ['Turkish lira', 'TRY', '949', '₺'],
    ['Trinidad and Tobago dollar', 'TTD', '780', '$'],
    ['New Taiwan dollar', 'TWD', '901', '$'],
    ['Tanzanian shilling', 'TZS', '834', 'Sh'],
    ['Ukrainian hryvnia', 'UAH', '980', '₴'],
    ['Ugandan shilling', 'UGX', '800', 'Sh'],
    ['United States dollar', 'USD', '840', '$'],
    ['Uruguayan peso', 'UYU', '858', '$'],
    ['Uzbekistani soʻm', 'UZS', '860', 'soʻm'],
    ['Venezuelan bolívar soberano', 'VES', '928', 'Bs. S.'],
    ['Vietnamese đồng', 'VND', '704', '₫'],
    ['Vanuatu vatu', 'VUV', '548', 'Vt'],
    ['Samoan tālā', 'WST', '882', 'T'],
    ['Central African CFA franc', 'XAF', '950', 'Fr'],
    ['East Caribbean dollar', 'XCD', '951', '$'],
    ['West African CFA franc', 'XOF', '952', 'Fr'],
    ['CFP franc', 'XPF', '953', 'Fr'],
  ],
}

export const getVariations = getVariationsCore(dataset)
export const getVariationItems = (variationKey: VariationKey | string = VariationKey.NAME) => getVariationItemsCore(dataset)(variationKey)
export const getItemVariation = (
  value: string,
  variationKey: VariationKey = VariationKey.NAME,
) => getItemVariationCore(dataset, 'Currency')(value, variationKey)
