import {
  getVariations as getVariationsCore,
  getVariationItems as getVariationItemsCore,
  getItemVariation as getItemVariationCore,
} from '@standardsets/core'

export enum VariationKey {
  COUNTRY_NAME = 'countryName',
  OFFICIAL_STATE_NAME = 'officialStateName',
  TWO_LETTER_CODE = 'twoLetterCode',
  THREE_LETTER_CODE = 'threeLetterCode',
  NUMERIC_CODE = 'numericCode',
  CC_TLD = 'ccTLD',
}

export const dataset = {
  name: 'Countries',
  description: '',
  variations: [
    {
      name: 'Country Name',
      description: '',
      key: VariationKey.COUNTRY_NAME,
      locale: 'en-US',
      index: 0,
    },
    {
      name: 'Official State Name',
      description: '',
      key: VariationKey.OFFICIAL_STATE_NAME,
      locale: 'en-US',
      index: 1,
    },
    {
      name: 'Two Letter Code',
      description: '',
      key: VariationKey.TWO_LETTER_CODE,
      locale: 'en-US',
      index: 2,
    },
    {
      name: 'Three-letter Code',
      description: '',
      key: VariationKey.THREE_LETTER_CODE,
      locale: 'en-US',
      index: 3,
    },
    {
      name: 'Numeric Code',
      description: '',
      key: VariationKey.NUMERIC_CODE,
      locale: 'en-US',
      index: 4,
    },
    {
      name: 'Country Code Top Level Domain (ccTLD)',
      description: '',
      key: VariationKey.CC_TLD,
      locale: 'en-US',
      index: 5,
    }
  ],
  data: [
    ['Afghanistan', 'The Islamic Republic of Afghanistan', 'AF', 'AFG', '004', '.af'],
    ['Åland Islands', 'Åland', 'AX', 'ALA', '248', '.ax'],
    ['Albania', 'The Republic of Albania', 'AL', 'ALB', '008', '.al'],
    ['Algeria', 'The People\'s Democratic Republic of Algeria', 'DZ', 'DZA', '012', '.dz'],
    ['American Samoa', 'American Samoa', 'AS', 'ASM', '016', '.as'],
    ['Andorra', 'The Principality of Andorra', 'AD', 'AND', '020', '.ad'],
    ['Angola', 'The Republic of Angola', 'AO', 'AGO', '024', '.ao'],
    ['Anguilla', 'Anguilla', 'AI', 'AIA', '660', '.ai'],
    ['Antarctica', 'Antarctica (the territory South of 60 deg S)', 'AQ', 'ATA', '010', '.aq'],
    ['Antigua and Barbuda', 'Antigua and Barbuda', 'AG', 'ATG', '028', '.ag'],
    ['Argentina', 'The Argentine Republic', 'AR', 'ARG', '032', '.ar'],
    ['Armenia', 'The Republic of Armenia', 'AM', 'ARM', '051', '.am'],
    ['Aruba', 'Aruba', 'AW', 'ABW', '533', '.aw'],
    ['Australia', 'The Commonwealth of Australia', 'AU', 'AUS', '036', '.au'],
    ['Austria', 'The Republic of Austria', 'AT', 'AUT', '040', '.at'],
    ['Azerbaijan', 'The Republic of Azerbaijan', 'AZ', 'AZE', '031', '.az'],
    ['Bahamas', 'The Commonwealth of The Bahamas', 'BS', 'BHS', '044', '.bs'],
    ['Bahrain', 'The Kingdom of Bahrain', 'BH', 'BHR', '048', '.bh'],
    ['Bangladesh', 'The People\'s Republic of Bangladesh', 'BD', 'BGD', '050', '.bd'],
    ['Barbados', 'Barbados', 'BB', 'BRB', '052', '.bb'],
    ['Belarus', 'The Republic of Belarus', 'BY', 'BLR', '112', '.by'],
    ['Belgium', 'The Kingdom of Belgium', 'BE', 'BEL', '056', '.be'],
    ['Belize', 'Belize', 'BZ', 'BLZ', '084', '.bz'],
    ['Benin', 'The Republic of Benin', 'BJ', 'BEN', '204', '.bj'],
    ['Bermuda', 'Bermuda', 'BM', 'BMU', '060', '.bm'],
    ['Bhutan', 'The Kingdom of Bhutan', 'BT', 'BTN', '064', '.bt'],
    ['Bolivia', 'The Plurinational State of Bolivia', 'BO', 'BOL', '068', '.bo'],
    ['Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', '535', '.bq'],
    ['Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'BA', 'BIH', '070', '.ba'],
    ['Botswana', 'The Republic of Botswana', 'BW', 'BWA', '072', '.bw'],
    ['Bouvet Island', 'Bouvet Island (Bouvetoya)', 'BV', 'BVT', '074', '.bv'],
    ['Brazil', 'The Federative Republic of Brazil', 'BR', 'BRA', '076', '.br'],
    ['British Indian Ocean Territory', 'British Indian Ocean Territory (Chagos Archipelago)', 'IO', 'IOT', '086', '.io'],
    ['Brunei Darussalam', 'Brunei Darussalam', 'BN', 'BRN', '096', '.bn'],
    ['Bulgaria', 'The Republic of Bulgaria', 'BG', 'BGR', '100', '.bg'],
    ['Burkina Faso', 'Burkina Faso', 'BF', 'BFA', '854', '.bf'],
    ['Burundi', 'The Republic of Burundi', 'BI', 'BDI', '108', '.bi'],
    ['Cambodia', 'The Kingdom of Cambodia', 'KH', 'KHM', '116', '.kh'],
    ['Cameroon', 'The Republic of Cameroon', 'CM', 'CMR', '120', '.cm'],
    ['Canada', 'Canada', 'CA', 'CAN', '124', '.ca'],
    ['Cape Verde', 'The Republic of Cape Verde', 'CV', 'CPV', '132', '.cv'],
    ['Cayman Islands', 'The Cayman Islands', 'KY', 'CYM', '136', '.ky'],
    ['Central African Republic', 'The Central African Republic', 'CF', 'CAF', '140', '.cf'],
    ['Chad', 'The Republic of Chad', 'TD', 'TCD', '148', '.td'],
    ['Chile', 'The Republic of Chile', 'CL', 'CHL', '152', '.cl'],
    ['China', 'The People\'s Republic of China', 'CN', 'CHN', '156', '.cn'],
    ['Christmas Island', 'Christmas Island', 'CX', 'CXR', '162', '.cx'],
    ['Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', 'CC', 'CCK', '166', '.cc'],
    ['Colombia', 'The Republic of Colombia', 'CO', 'COL', '170', '.co'],
    ['Comoros', 'The Union of the Comoros', 'KM', 'COM', '174', '.km'],
    ['Congo', 'The Republic of the Congo', 'CG', 'COG', '178', '.cg'],
    ['Congo', 'The Democratic Republic of the Congo', 'CD', 'COD', '180', '.cd'],
    ['Cook Islands', 'The Cook Islands', 'CK', 'COK', '184', '.ck'],
    ['Costa Rica', 'The Republic of Costa Rica', 'CR', 'CRI', '188', '.cr'],
    ['Côte d\'Ivoire', 'Côte d\'Ivoire', 'CI', 'CIV', '384', '.ci'],
    ['Croatia', 'The Republic of Croatia', 'HR', 'HRV', '191', '.hr'],
    ['Cuba', 'The Republic of Cuba', 'CU', 'CUB', '192', '.cu'],
    ['Curaçao', 'Curaçao', 'CW', 'CUW', '531', '.cw'],
    ['Cyprus', 'The Republic of Cyprus', 'CY', 'CYP', '196', '.cy'],
    ['Czech Republic', 'The Czech Republic', 'CZ', 'CZE', '203', '.cz'],
    ['Denmark', 'The Kingdom of Denmark', 'DK', 'DNK', '208', '.dk'],
    ['Djibouti', 'The Republic of Djibouti', 'DJ', 'DJI', '262', '.dj'],
    ['Dominica', 'The Commonwealth of Dominica', 'DM', 'DMA', '212', '.dm'],
    ['Dominican Republic', 'The Dominican Republic', 'DO', 'DOM', '214', '.do'],
    ['Ecuador', 'The Republic of Ecuador', 'EC', 'ECU', '218', '.ec'],
    ['Egypt', 'The Arab Republic of Egypt', 'EG', 'EGY', '818', '.eg'],
    ['El Salvador', 'The Republic of El Salvador', 'SV', 'SLV', '222', '.sv'],
    ['Equatorial Guinea', 'The Republic of Equatorial Guinea', 'GQ', 'GNQ', '226', '.gq'],
    ['Eritrea', 'The State of Eritrea', 'ER', 'ERI', '232', '.er'],
    ['Estonia', 'The Republic of Estonia', 'EE', 'EST', '233', '.ee'],
    ['Ethiopia', 'The Federal Democratic Republic of Ethiopia', 'ET', 'ETH', '231', '.et'],
    ['Falkland Islands (Malvinas)', 'Falkland Islands (Malvinas)', 'FK', 'FLK', '238', '.fk'],
    ['Faroe Islands', 'The Faroe Islands', 'FO', 'FRO', '234', '.fo'],
    ['Fiji', 'The Republic of Fiji', 'FJ', 'FJI', '242', '.fj'],
    ['Finland', 'The Republic of Finland', 'FI', 'FIN', '246', '.fi'],
    ['France', 'The French Republic', 'FR', 'FRA', '250', '.fr'],
    ['French Guiana', 'French Guiana', 'GF', 'GUF', '254', '.gf'],
    ['French Polynesia', 'French Polynesia', 'PF', 'PYF', '258', '.pf'],
    ['French Southern Territories', 'French Southern Territories', 'TF', 'ATF', '260', '.tf'],
    ['Gabon', 'The Gabonese Republic', 'GA', 'GAB', '266', '.ga'],
    ['Gambia', 'The Republic of The Gambia', 'GM', 'GMB', '270', '.gm'],
    ['Georgia', 'Georgia', 'GE', 'GEO', '268', '.ge'],
    ['Germany', 'The Federal Republic of Germany', 'DE', 'DEU', '276', '.de'],
    ['Ghana', 'The Republic of Ghana', 'GH', 'GHA', '288', '.gh'],
    ['Gibraltar', 'Gibraltar', 'GI', 'GIB', '292', '.gi'],
    ['Greece', 'The Hellenic Republic', 'GR', 'GRC', '300', '.gr'],
    ['Greenland', 'Greenland', 'GL', 'GRL', '304', '.gl'],
    ['Grenada', 'Grenada', 'GD', 'GRD', '308', '.gd'],
    ['Guadeloupe', 'Guadeloupe', 'GP', 'GLP', '312', '.gp'],
    ['Guam', 'Guam', 'GU', 'GUM', '316', '.gu'],
    ['Guatemala', 'The Republic of Guatemala', 'GT', 'GTM', '320', '.gt'],
    ['Guernsey', 'Guernsey', 'GG', 'GGY', '831', '.gg'],
    ['Guinea', 'The Republic of Guinea', 'GN', 'GIN', '324', '.gn'],
    ['Guinea-Bissau', 'The Republic of Guinea-Bissau', 'GW', 'GNB', '624', '.gw'],
    ['Guyana', 'The Co-operative Republic of Guyana', 'GY', 'GUY', '328', '.gy'],
    ['Haiti', 'The Republic of Haiti', 'HT', 'HTI', '332', '.ht'],
    ['Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', 'HM', 'HMD', '334', '.hm'],
    ['Holy See (Vatican City State)', 'The Holy See (Vatican City State)', 'VA', 'VAT', '336', '.va'],
    ['Honduras', 'The Republic of Honduras', 'HN', 'HND', '340', '.hn'],
    ['Hong Kong', 'Hong Kong', 'HK', 'HKG', '344', '.hk'],
    ['Hungary', 'The Republic of Hungary', 'HU', 'HUN', '348', '.hu'],
    ['Iceland', 'The Republic of Iceland', 'IS', 'ISL', '352', '.is'],
    ['India', 'The Republic of India', 'IN', 'IND', '356', '.in'],
    ['Indonesia', 'The Republic of Indonesia', 'ID', 'IDN', '360', '.id'],
    ['Iran', 'The Islamic Republic of Iran', 'IR', 'IRN', '364', '.ir'],
    ['Iraq', 'The Republic of Iraq', 'IQ', 'IRQ', '368', '.iq'],
    ['Ireland', 'Ireland', 'IE', 'IRL', '372', '.ie'],
    ['Isle of Man', 'The Isle of Man', 'IM', 'IMN', '833', '.im'],
    ['Israel', 'The State of Israel', 'IL', 'ISR', '376', '.il'],
    ['Italy', 'The Italian Republic', 'IT', 'ITA', '380', '.it'],
    ['Jamaica', 'Jamaica', 'JM', 'JAM', '388', '.jm'],
    ['Japan', 'Japan', 'JP', 'JPN', '392', '.jp'],
    ['Jersey', 'Jersey', 'JE', 'JEY', '832', '.je'],
    ['Jordan', 'The Hashemite Kingdom of Jordan', 'JO', 'JOR', '400', '.jo'],
    ['Kazakhstan', 'The Republic of Kazakhstan', 'KZ', 'KAZ', '398', '.kz'],
    ['Kenya', 'The Republic of Kenya', 'KE', 'KEN', '404', '.ke'],
    ['Kiribati', 'The Republic of Kiribati', 'KI', 'KIR', '296', '.ki'],
    ['Korea', 'The Democratic People\'s Republic of Korea', 'KP', 'PRK', '408', '.kp'],
    ['Korea', 'The Republic of Korea', 'KR', 'KOR', '410', '.kr'],
    ['Kuwait', 'The State of Kuwait', 'KW', 'KWT', '414', '.kw'],
    ['Kyrgyzstan', 'The Kyrgyz Republic', 'KG', 'KGZ', '417', '.kg'],
    ['Lao', 'The Lao People\'s Democratic Republic', 'LA', 'LAO', '418', '.la'],
    ['Latvia', 'The Republic of Latvia', 'LV', 'LVA', '428', '.lv'],
    ['Lebanon', 'The Lebanese Republic', 'LB', 'LBN', '422', '.lb'],
    ['Lesotho', 'The Kingdom of Lesotho', 'LS', 'LSO', '426', '.ls'],
    ['Liberia', 'The Republic of Liberia', 'LR', 'LBR', '430', '.lr'],
    ['Libya', 'The State of Libya', 'LY', 'LBY', '434', '.ly'],
    ['Liechtenstein', 'The Principality of Liechtenstein', 'LI', 'LIE', '438', '.li'],
    ['Lithuania', 'The Republic of Lithuania', 'LT', 'LTU', '440', '.lt'],
    ['Luxembourg', 'The Grand Duchy of Luxembourg', 'LU', 'LUX', '442', '.lu'],
    ['Macao', 'Macao', 'MO', 'MAC', '446', '.mo'],
    ['Macedonia', 'The Former Yugoslav Republic of Macedonia', 'MK', 'MKD', '807', '.mk'],
    ['Madagascar', 'The Republic of Madagascar', 'MG', 'MDG', '450', '.mg'],
    ['Malawi', 'The Republic of Malawi', 'MW', 'MWI', '454', '.mw'],
    ['Malaysia', 'Malaysia', 'MY', 'MYS', '458', '.my'],
    ['Maldives', 'The Republic of Maldives', 'MV', 'MDV', '462', '.mv'],
    ['Mali', 'The Republic of Mali', 'ML', 'MLI', '466', '.ml'],
    ['Malta', 'The Republic of Malta', 'MT', 'MLT', '470', '.mt'],
    ['Marshall Islands', 'The Republic of the Marshall Islands', 'MH', 'MHL', '584', '.mh'],
    ['Martinique', 'Martinique', 'MQ', 'MTQ', '474', '.mq'],
    ['Mauritania', 'The Islamic Republic of Mauritania', 'MR', 'MRT', '478', '.mr'],
    ['Mauritius', 'The Republic of Mauritius', 'MU', 'MUS', '480', '.mu'],
    ['Mayotte', 'Mayotte', 'YT', 'MYT', '175', '.yt'],
    ['Mexico', 'The United Mexican States', 'MX', 'MEX', '484', '.mx'],
    ['Micronesia', 'The Federated States of Micronesia', 'FM', 'FSM', '583', '.fm'],
    ['Moldova', 'The Republic of Moldova', 'MD', 'MDA', '498', '.md'],
    ['Monaco', 'The Principality of Monaco', 'MC', 'MCO', '492', '.mc'],
    ['Mongolia', 'Mongolia', 'MN', 'MNG', '496', '.mn'],
    ['Montenegro', 'Montenegro', 'ME', 'MNE', '499', '.me'],
    ['Montserrat', 'Montserrat', 'MS', 'MSR', '500', '.ms'],
    ['Morocco', 'The Kingdom of Morocco', 'MA', 'MAR', '504', '.ma'],
    ['Mozambique', 'The Republic of Mozambique', 'MZ', 'MOZ', '508', '.mz'],
    ['Myanmar', 'The Republic of the Union of Myanmar', 'MM', 'MMR', '104', '.mm'],
    ['Namibia', 'The Republic of Namibia', 'NA', 'NAM', '516', '.na'],
    ['Nauru', 'The Republic of Nauru', 'NR', 'NRU', '520', '.nr'],
    ['Nepal', 'The Federal Democratic Republic of Nepal', 'NP', 'NPL', '524', '.np'],
    ['Netherlands', 'The Kingdom of the Netherlands', 'NL', 'NLD', '528', '.nl'],
    ['New Caledonia', 'New Caledonia', 'NC', 'NCL', '540', '.nc'],
    ['New Zealand', 'New Zealand', 'NZ', 'NZL', '554', '.nz'],
    ['Nicaragua', 'The Republic of Nicaragua', 'NI', 'NIC', '558', '.ni'],
    ['Niger', 'The Republic of Niger', 'NE', 'NER', '562', '.ne'],
    ['Nigeria', 'The Federal Republic of Nigeria', 'NG', 'NGA', '566', '.ng'],
    ['Niue', 'Niue', 'NU', 'NIU', '570', '.nu'],
    ['Norfolk Island', 'Norfolk Island', 'NF', 'NFK', '574', '.nf'],
    ['Northern Mariana Islands', 'The Commonwealth of the Northern Mariana Islands', 'MP', 'MNP', '580', '.mp'],
    ['Norway', 'The Kingdom of Norway', 'NO', 'NOR', '578', '.no'],
    ['Oman', 'The Sultanate of Oman', 'OM', 'OMN', '512', '.om'],
    ['Pakistan', 'The Islamic Republic of Pakistan', 'PK', 'PAK', '586', '.pk'],
    ['Palau', 'The Republic of Palau', 'PW', 'PLW', '585', '.pw'],
    ['Palentine, State of', 'Palentine, State of', 'PS', 'PSE', '275', '.ps'],
    ['Panama', 'The Republic of Panama', 'PA', 'PAN', '591', '.pa'],
    ['Papua New Guinea', 'Independent State of Papua New Guinea', 'PG', 'PNG', '598', '.pg'],
    ['Paraguay', 'The Republic of Paraguay', 'PY', 'PRY', '600', '.py'],
    ['Peru', 'The Republic of Peru', 'PE', 'PER', '604', '.pe'],
    ['Philippines', 'The Republic of the Philippines', 'PH', 'PHL', '608', '.ph'],
    ['Pitcairn', 'Pitcairn', 'PN', 'PCN', '612', '.pn'],
    ['Poland', 'The Republic of Poland', 'PL', 'POL', '616', '.pl'],
    ['Portugal', 'The Portuguese Republic', 'PT', 'PRT', '620', '.pt'],
    ['Puerto Rico', 'Puerto Rico', 'PR', 'PRI', '630', '.pr'],
    ['Qatar', 'The State of Qatar', 'QA', 'QAT', '634', '.qa'],
    ['Reunion', 'Reunion', 'RE', 'REU', '638', '.re'],
    ['Romania', 'Romania', 'RO', 'ROU', '642', '.ro'],
    ['Russia', 'The Russian Federation', 'RU', 'RUS', '643', '.ru'],
    ['Rwanda', 'The Republic of Rwanda', 'RW', 'RWA', '646', '.rw'],
    ['Saint Barthélemy', 'The Collectivity of Saint-Barthélemy', 'BL', 'BLM', '652', '.bl'],
    ['Saint Helena', 'Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', '654', '.sh'],
    ['Saint Kitts and Nevis', 'Saint Kitts and Nevis', 'KN', 'KNA', '659', '.kn'],
    ['Saint Lucia', 'Saint Lucia', 'LC', 'LCA', '662', '.lc'],
    ['Saint Martin', 'Saint Martin', 'MF', 'MAF', '663', '.mf'],
    ['Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', 'PM', 'SPM', '666', '.pm'],
    ['Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'VC', 'VCT', '670', '.vc'],
    ['Samoa', 'The Independent State of Samoa', 'WS', 'WSM', '882', '.ws'],
    ['San Marino', 'The Republic of San Marino', 'SM', 'SMR', '674', '.sm'],
    ['Sao Tome and Principe', 'The Democratic Republic of Sao Tome and Principe', 'ST', 'STP', '678', '.st'],
    ['Saudi Arabia', 'The Kingdom of Saudi Arabia', 'SA', 'SAU', '682', '.sa'],
    ['Senegal', 'The Republic of Senegal', 'SN', 'SEN', '686', '.sn'],
    ['Serbia', 'The Republic of Serbia', 'RS', 'SRB', '688', '.rs'],
    ['Seychelles', 'The Republic of Seychelles', 'SC', 'SYC', '690', '.sc'],
    ['Sierra Leone', 'The Republic of Sierra Leone', 'SL', 'SLE', '694', '.sl'],
    ['Singapore', 'The Republic of Singapore', 'SG', 'SGP', '702', '.sg'],
    ['Sint Maarten', 'Sint Maarten', 'SX', 'SXM', '534', '.sx'],
    ['Slovakia', 'The Slovak Republic', 'SK', 'SVK', '703', '.sk'],
    ['Slovenia', 'The Republic of Slovenia', 'SI', 'SVN', '705', '.si'],
    ['Solomon Islands', 'Solomon Islands', 'SB', 'SLB', '090', '.sb'],
    ['Somalia', 'The Federal Republic of Somalia', 'SO', 'SOM', '706', '.so'],
    ['South Africa', 'The Republic of South Africa', 'ZA', 'ZAF', '710', '.za'],
    ['South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands', 'GS', 'SGS', '239', '.gs'],
    ['South Sudan', 'The Republic of South Sudan', 'SS', 'SSD', '728', '.ss'],
    ['Spain', 'The Kingdom of Spain', 'ES', 'ESP', '724', '.es'],
    ['Sri Lanka', 'The Democratic Socialist Republic of Sri Lanka', 'LK', 'LKA', '144', '.lk'],
    ['Sudan', 'The Republic of the Sudan', 'SD', 'SDN', '729', '.sd'],
    ['Suriname', 'The Republic of Suriname', 'SR', 'SUR', '740', '.sr'],
    ['Svalbard and Jan Mayen', 'Svalbard and Jan Mayen', 'SJ', 'SJM', '744', '.sj'],
    ['Swaziland', 'The Kingdom of Swaziland', 'SZ', 'SWZ', '748', '.sz'],
    ['Sweden', 'The Kingdom of Sweden', 'SE', 'SWE', '752', '.se'],
    ['Switzerland', 'The Swiss Confederation', 'CH', 'CHE', '756', '.ch'],
    ['Syria', 'The Syrian Arab Republic', 'SY', 'SYR', '760', '.sy'],
    ['Taiwan', 'Taiwan', 'TW', 'TWN', '158', '.tw'],
    ['Tajikistan', 'The Republic of Tajikistan', 'TJ', 'TJK', '762', '.tj'],
    ['Tanzania', 'The United Republic of Tanzania', 'TZ', 'TZA', '834', '.tz'],
    ['Thailand', 'The Kingdom of Thailand', 'TH', 'THA', '764', '.th'],
    ['Timor-Leste', 'Democratic Republic of Timor-Leste', 'TL', 'TLS', '626', '.tl'],
    ['Togo', 'The Togolese Republic', 'TG', 'TGO', '768', '.tg'],
    ['Tokelau', 'Tokelau', 'TK', 'TKL', '772', '.tk'],
    ['Tonga', 'The Kingdom of Tonga', 'TO', 'TON', '776', '.to'],
    ['Trinidad and Tobago', 'The Republic of Trinidad and Tobago', 'TT', 'TTO', '780', '.tt'],
    ['Tunisia', 'The Republic of Tunisia', 'TN', 'TUN', '788', '.tn'],
    ['Turkey', 'The Republic of Turkey', 'TR', 'TUR', '792', '.tr'],
    ['Turkmenistan', 'Turkmenistan', 'TM', 'TKM', '795', '.tm'],
    ['Turks and Caicos Islands', 'The Turks and Caicos Islands', 'TC', 'TCA', '796', '.tc'],
    ['Tuvalu', 'Tuvalu', 'TV', 'TUV', '798', '.tv'],
    ['Uganda', 'The Republic of Uganda', 'UG', 'UGA', '800', '.ug'],
    ['Ukraine', 'Ukraine', 'UA', 'UKR', '804', '.ua'],
    ['United Arab Emirates', 'The United Arab Emirates', 'AE', 'ARE', '784', '.ae'],
    ['United Kingdom', 'The United Kingdom of Great Britain and Northern Ireland', 'GB', 'GBR', '826', '.uk'],
    ['United States', 'The United States of America', 'US', 'USA', '840', '.us'],
    ['United States Minor Outlying Islands', 'United States Minor Outlying Islands', 'UM', 'UMI', '581', '.um'],
    ['Uruguay', 'The Eastern Republic of Uruguay', 'UY', 'URY', '858', '.uy'],
    ['Uzbekistan', 'The Republic of Uzbekistan', 'UZ', 'UZB', '860', '.uz'],
    ['Vanuatu', 'The Republic of Vanuatu', 'VU', 'VUT', '548', '.vu'],
    ['Venezuela', 'The Bolivarian Republic of Venezuela', 'VE', 'VEN', '862', '.ve'],
    ['Viet Nam', 'The Socialist Republic of Viet Nam', 'VN', 'VNM', '704', '.vn'],
    ['Virgin Islands, British', 'British Virgin Islands', 'VG', 'VGB', '092', '.vg'],
    ['Virgin Islands, U.S.', 'United States Virgin Islands', 'VI', 'VIR', '850', '.vi'],
    ['Wallis and Futuna', 'Wallis and Futuna', 'WF', 'WLF', '876', '.wf'],
    ['Western Sahara', 'Western Sahara', 'EH', 'ESH', '732', '.eh'],
    ['Yemen', 'The Republic of Yemen', 'YE', 'YEM', '887', '.ye'],
    ['Zambia', 'The Republic of Zambia', 'ZM', 'ZMB', '894', '.zm'],
    ['Zimbabwe', 'The Republic of Zimbabwe', 'ZW', 'ZWE', '716', '.zw'],
  ]
}

export const getVariations = getVariationsCore(dataset)
export const getVariationItems = (variationKey: VariationKey | string = VariationKey.COUNTRY_NAME) => getVariationItemsCore(dataset)(variationKey)
export const getItemVariation = (
  value: string,
  variationKey: VariationKey = VariationKey.COUNTRY_NAME,
) => getItemVariationCore(dataset, 'Country')(value, variationKey)
